name: Build Windows

on:
  workflow_dispatch:

  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:
   Build-Windows:
     runs-on: windows-2019
     env:
      pkgver: '9.1.0'
      patch:  '00-qemu91x-mesa-glide.patch'
      
     steps:  
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: Install Wrapper dependencies
       uses: msys2/setup-msys2@v2
       with:
          msystem: MINGW32
     - shell: msys2 {0}
       run: |
        pacman -Sy --noconfirm --needed \
        base-devel \
        vim \
        perl \
        mingw-w64-i686-tools \
        mingw-w64-i686-binutils \
        mingw-w64-i686-gcc \
        
     - name: Build 3dfx wrappers
       run: |
        cd wrappers/3dfx
        mkdir build && cd build
        dir
        bash ../../../scripts/conf-wrapper
        make && make clean
     - name: Make mesa build dir

     - name: Build Mesa wrappers 
       working-directory: ./wrappers/mesa
       run: |
        cd wrappers/3dfx
        mkdir build && cd build
        dir
        bash ../../../scripts/conf-wrapper
        make && make clean
     - name: Uploading file
       uses: actions/upload-artifact@v4
       with:
        name: bin-wrappers-${{ env.pkgver }}-artifact
        path: ./wrappers

        

     

     


        
