name: Build Windows

on:
  workflow_dispatch:

  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:

   
   Build-Windows:
   
     runs-on: windows-2019       
     env:
      pkgver: '9.1.0'
      patch:  '00-qemu91x-mesa-glide.patch'
      
     steps:  
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: Setup MSYS2 (mingw32)
       uses: msys2/setup-msys2@v2
       with:
         msystem: MINGW32
         update: true
         install: >-
            base
            base-devel
            coreutils
            git
            grep
            perl
            rsync
            sed
            unzip
            vim
            mingw-w64-i686-tools
            mingw-w64-i686-binutils
            mingw-w64-i686-gcc       

     - name: Adding watcom support
       shell: msys2 {0}
       run:  |
         dir
         wget -q https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.xz
         mkdir watcom
         tar xf ow-snapshot.tar.xz -C watcom
         export WATCOM=$(pwd)/watcom
         export PATH=$WATCOM/binnt64:$WATCOM/bint:$PATH
         export EDPATH=$WATCOM/eddat
         export INCLUDE=$WATCOM/h/nt
         dir

     - name: Adding djgpp support
       shell: msys2 {0}
       run: |
         dir
         wget -q https://github.com/andrewwutw/build-djgpp/releases/download/v3.4/djgpp-mingw-gcc1220.zip
         unzip -q djgpp-mingw-gcc1220.zip
         cp djgpp/i586-pc-msdosdjgpp/bin/dxe* djgpp/bin
         export DJGPP_PREFIX=$(pwd)/djgpp
         export PATH=$(pwd)/djgpp/bin:$PATH
         export DJDIR=$(pwd)/djgpp/i586-pc-msdosdjgpp
         dir
         printenv

     - name: Build 3dfx wrappers
       shell: msys2 {0}
       run: |
        export WATCOM=$(pwd)/watcom
        export PATH=$WATCOM/binnt64:$WATCOM/bint:$PATH
        export EDPATH=$WATCOM/eddat
        export INCLUDE=$WATCOM/h/nt
        export DJGPP_PREFIX=$(pwd)/djgpp
        export PATH=$(pwd)/djgpp/bin:$PATH
        export DJDIR=$(pwd)/djgpp/i586-pc-msdosdjgpp
        printenv
        cd wrappers/3dfx
        mkdir build && cd build
        dir
        bash ../../../scripts/conf_wrapper
        make && make clean

     - name: Build Mesa wrappers
       shell: msys2 {0}
       run: |
        export WATCOM=$(pwd)/watcom
        export PATH=$WATCOM/binnt64:$WATCOM/bint:$PATH
        export EDPATH=$WATCOM/eddat
        export INCLUDE=$WATCOM/h/nt
        export DJGPP_PREFIX=$(pwd)/djgpp
        export PATH=$(pwd)/djgpp/bin:$PATH
        export DJDIR=$(pwd)/djgpp/i586-pc-msdosdjgpp
        printenv
        cd ../../..
        cd wrappers/mesa
        mkdir build && cd build
        dir
        bash ../../../scripts/conf_wrapper
        make && make clean
        
     - name: Uploading file
       uses: actions/upload-artifact@v4
       with:
        name: bin-wrappers-${{ env.pkgver }}-artifact
        path: ./wrappers

        

     

     


        
