# Wrapper Disk first then binary i hope 
# wah
name: Build Windows

on:
  workflow_dispatch:

  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

jobs:
   Build-Windows:
     runs-on: windows-2019
     env:
      pkgver: '9.1.0'
      patch:  '00-qemu91x-mesa-glide.patch'
      
     steps:  
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Install Wrapper dependencies
       uses: msys2/setup-msys2@v2
       with:
          msystem: MINGW32
     - shell: msys2 {0}
       run: |
        pacman -Sy --noconfirm --needed \
        base-devel \
        vim \
        {MINGW_PACKAGE_PREFIX}-tools \
        {MINGW_PACKAGE_PREFIX}-binutils \
        {MINGW_PACKAGE_PREFIX}-gcc \
        
     - name: Run 3dfx
       uses: msys2/setup-msys2@v2
       with:
          msystem: MINGW32
     - shell: msys2 {0}
       working-directory: ./wrappers/3dfx
       run: |
        mkdir build
        cd build
        bash ../../../scripts/conf-wrapper

     

     


        
